name: phone_number
description: Flutter plugin for parsing, formatting and validating international
  phone numbers.
version: 2.0.0-dev.1
homepage: https://github.com/flutter-form-builder-ecosystem
repository: https://github.com/flutter-form-builder-ecosystem/phone_number
issues: https://github.com/flutter-form-builder-ecosystem/phone_number/issues
funding: 
  - https://opencollective.com/flutter-form-builder-ecosystem

environment:
  sdk: ">=2.17.0 <3.0.0"
  flutter: ">=3.10.0"

dependencies:
  flutter:
    sdk: flutter
  meta: ^1.9.1

dev_dependencies:
  flutter_lints: ^2.0.1

flutter:
  plugin:
    platforms:
      android:
        package: com.julienvignali.phone_number
        pluginClass: PhoneNumberPlugin
      ios:
        pluginClass: PhoneNumberPlugin
