name: phone_number
description: Flutter plugin for parsing, formatting and validating international
  phone numbers.
version: 0.11.0
homepage: https://github.com/nashfive/phone_number

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.20.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  js: ^0.6.3
  meta: ^1.3.0

dev_dependencies:
  pedantic: ^1.11.0

flutter:

  assets:
    - assets/js/libphonenumber.js

  plugin:
    platforms:
      android:
        package: com.julienvignali.phone_number
        pluginClass: PhoneNumberPlugin
      ios:
        pluginClass: PhoneNumberPlugin
      web:
        pluginClass: PhoneNumberPlugin
        fileName: web/phone_number_web.dart
