name: phone_number
description: Flutter plugin for phone number validation
version: 0.3.0
author: Julien Vignali <contact@julienvignali.com>
homepage: https://github.com/nashfive/phone_number

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

flutter:
  plugin:
    androidPackage: com.julienvignali.phone_number
    pluginClass: PhoneNumberPlugin

