name: phone_number
description: Flutter plugin for parsing, formatting and validating international
  phone numbers.
version: 0.9.0+2
homepage: https://github.com/nashfive/phone_number

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.20.0"

dependencies:
  flutter:
    sdk: flutter
  meta: ^1.3.0

dev_dependencies:
  pedantic: ^1.11.0

flutter:
  plugin:
    platforms:
      android:
        package: com.julienvignali.phone_number
        pluginClass: PhoneNumberPlugin
      ios:
        pluginClass: PhoneNumberPlugin
