name: phone_number
description: Flutter plugin for parsing, formatting and validating international phone numbers.
version: 0.6.2+1
homepage: https://github.com/nashfive/phone_number

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  mockito: ^4.1.0
  pedantic: ^1.0.0
  flutter_test:
    sdk: flutter
  e2e: ^0.4.0
  flutter_driver:
    sdk: flutter
   
flutter:
  plugin:
    platforms:
      android:
        package: com.julienvignali.phone_number
        pluginClass: PhoneNumberPlugin
      ios:
        pluginClass: PhoneNumberPlugin

environment:
  sdk: ">=2.3.0 <3.0.0"
  flutter: ">=1.12.13+hotfix.6 <2.0.0"
